### PR TITLE
Iframe embed

### LINKED ISSUE #89: iframe embed (for the sake of scholar articles)
@caseyedavis12 
- Is this for internal, on-site usage only, or should it be usable outside as well? (Default rails security prevents it from being used outside, but that can be overridden.)
- Is it just the media, or do you want a scrolling transcript as well?

### PR DESCRIPTION
**Pull request by mccalluc**
Fix #89. @afred?

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc this is for using `<iframe>` within cmless markdown?

Also.. i know we're explicitly hiding the transcript here.. but if we weren't, we'd have nested iframes, yes? I trust that won't cause any disruptions in the space-time continuum?

**Comment by mccalluc** [comment]
@afred:
- yes, within markdown. (note [this](https://github.com/WGBH/openvault3/pull/147/files#diff-1987a252ba3efe037c7bf36f9c6f16b1R4) if we want to use it outside.)
- Maybe there should be a separate controller, or maybe the erb code should check for a "hide-transcript" parameter, or maybe something else... but this seemed simplest at the time, and besides being unusable, there's no issue that I know of with nested iframes.

**Comment by caseyedavis12** [comment]
@mccalluc: can you tell me what code I should use in markdown to embed a video in an exhibit?

**Comment by mccalluc** [comment]
@caseyedavis12 : 
```html
<iframe src="/embed/your-id-here"></iframe>
```

Won't work on github, but that's what should work on the real site: It's a place to begin.

**Comment by afred** [comment]
@caseyedavis12 worth noting by going to `/embed/your-id-here` you should be able to see the content that will display inside of the `<iframe>`.

**Comment by caseyedavis12** [comment]
thanks @mccalluc and @afred: Yes, Chuck has shown me the embed URL before.

**Pull request merged**
