### PR TITLE
Adds a common method for rendering a 404 page

### PR DESCRIPTION
**Pull request by afred**
* Implements common 404 rendering method for Override and Catalog routes.
* Adds controller tests for Override and Catalog 404s.
* Adds a wee bit o styling.
* Simplifies contraint for Override routes.

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc here is another approach to the 404 stuff.

**Pros:**
  * common 404 method for any controller, without requiring a redirect through Override
  * uses main application layout for 404
  * does not supersede non-404 events

**Cons**
  * does not use a cmless markdown file for the 404 template.

**Comment by mccalluc** [comment]
@afred: Sorry to be slow getting to this. Could you check the behavior on 
- http://localhost:3000/exhibits/asdf
- http://localhost:3000/collections/vietnam/interviews.xml
- http://localhost:3000/catalog?f[access]=Available+Online
- http://localhost:3000/catalog?f[access][]=Available+Online&f[asdf]=asdf

... Or maybe where it works, it works, and we'll worry about these separately? I just don't know what the intended scope of this fix is.

(This in in dev mode. There's something I'm not understanding about the startup of production mode: it's like the old application is cached, and I need to find some way to clear it...)

**Comment by mccalluc** [comment]
hmm... Thinking some more: some of there are just blacklight being blacklight. In my mind, ideally, 500 really is a problem on the server, and an indication that something should be fixed: User input, no matter how bad should not be able to push us into a 500... but that is not the way BL works, I don't think. So do we override that, at the cost of more complexity? Or do we make the 500s pretty, but they stay 500s?

**Comment by afred** [comment]
I agree that 5xx should be returned if there really is a problem on the server.

However, I don't think it constitutes a problem on our end, if the user puts in a random URL that doesn't return anything. That should return 404.

If the user enters a URL that would normally return a resource, but due to some state of the application, it fails to...  then I think it would be appropriate to return 500.

**Comment by mccalluc** [comment]
Right, so I'm comfortable merging this because it makes some of the 404s a lot prettier, but if you'd like to keep it open until we think a user will never get a 500 with a malformed url, I'm ok with that too.

(I think we got started on this because of all the 500s we're seeing, rather than the 404s per se, so I want to be clear about goals.)

**Pull request merged**
