### PR TITLE
Update boston-tv-news.md

### PR DESCRIPTION
**Pull request by caseyedavis12**

### CODE REVIEW

**Comment by mccalluc** [comment]
@caseyedavis12 : The original image srcs you supplied are dead: the only thing in that directory is the photo of the guys and their van.

I've changed the urls to point at the usual thumbnail location... but they aren't there either. (It seems to me to make sense create thumbnails, so that at least for these six there are also thumbnails in the catalog.)

You could point to the thumbails in their present location, but we'd need to loosen security.

.... and stepping back a bit, are you sure this is the right approach at all? Why not use the usual machinery on this page, instead of hard coding the html? It'd be one more click for the user, but on the plus side they would get a much fuller list of the resources available?

... or we could just not do images: There's nothing wrong with a list.

I don't really care, but this can't be merged with dead image links.

**Comment by caseyedavis12** [comment]
@mccalluc: I had to leave for a meeting but the plan is for me to create those 6 images and name them the way I named them in markdown and put them in the appropriate folder on s3...
________________________________

**Comment by afred** [comment]
@caseyedavis12 tests are green, but I'm still not seeing the images. Please let me know when you get them up. If you already put them up, come let me know how/where you put them.

**Comment by caseyedavis12** [comment]
@mccalluc: Plan was to do it yesterday but I was sick. ALmost finished, though it looks like you have changed the URLs to the images in the md page. Will put the images in that folder.

**Comment by caseyedavis12** [comment]
@mccalluc: Images are in /catalog/asset-thumbnails now.

**Pull request merged**
