### PR TITLE
Updates Spring gem

### LINKED ISSUE #143: Fix gem version issue with Spring
Not sure if this is specific to me or what, but I get this error when trying to start a rails console:
```
/Users/andrew_myers/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.11.2/lib/bundler/runtime.rb:34:in `block in setup': You have already activated spring 1.6.2, but your Gemfile requires spring 1.3.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

**Done when** this doesn't happen on my machine anymore.

### PR DESCRIPTION
**Pull request by afred**
closes #143.

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc?

**Comment by mccalluc** [comment]
@afred: Shouldn't you pin the version you need in the Gemfile, and then have it rebuild the Gemfile.lock? Or is this case different?

**Comment by afred** [comment]
@mccalluc in this case, I think pinning _or_ updating the gem would work. I tried updating, and there weren't any conflicts, so might as well.

**Comment by mccalluc** [comment]
@afred: went ahead and added a version pin and did a `bundle install`: Without that I'd worry about some other update perhaps clobbering the Gemfile.lock and making things awkward for you again.

**Pull request merged**
