### PR TITLE
Solr highlight

### PR DESCRIPTION
**Pull request by mccalluc**
@caseyedavis12 : Would highlighting search terms in context be useful to users?
screen shot 2016-03-08 at 3 25 45 pm

If so, what should it look like?

@afred : This does make the index large, since the transcript needs to be stored, not just indexed. Is this a concern?

### CODE REVIEW

**Comment by caseyedavis12** [comment]
@mccalluc: I think that this would definitely help users. Would this highlight search terms in the transcript and the metadata record? What if we highlighted the search terms with a light transparent background using a color in the color palette?

**Comment by afred** [comment]
@mccalluc in your screen shot, which term did you search for?.. "evil"?

**Comment by afred** [comment]
@mccalluc I don't think we care about index size, except in how it affects performance and $$.

**Comment by afred** [comment]
@mccalluc I would put a specific class name on the markup that Solr injects to avoid style overlap, i.e. `<span class="solr-highlight">`

**Comment by afred** [comment]
I don't know if it's a good idea to add highlighted terms to the copy below the thumbnails in a grid view, for two reasons:
  1. The "Series; Program; Asset" displayed in the screen shot will actually be real titles, which oftentimes span multiple lines already.
  1. When highlighting the found terms, you want to surround it with some context, but I don't think it would be very useful to just grab X words on either side of the highlighted term. Google search results, for instance, appear to grab the containing sentence (and sometimes more). This is much more useful, but also much more verbose, and now we're putting a lot of words in the text below the thumbnail.

I could be convinced otherwise with a more robust visual example, but I feel if we try to do this as-is, we'd be messing with the grid view in undesirable ways.

thoughts @mccalluc @caseyedavis12?

**Comment by mccalluc** [comment]
Yeah, particularly if an outstanding goal is to make the rectangles more uniform, this is really pulling in the opposite direction. A google image search does not tell you anything about the context of your term in the results.

If we really wanted to present this information somehow, maybe it could be floated over the bottom of the image, something like the titles on the homepage?

**Comment by afred** [comment]
@mccalluc @caseyedavis12 is it ok to close this as a PR? We can keep the branch open for more exploration.

I think that highlighting found search terms inherently involves introducing significant amounts of additional text onto the search results page, which has more design considerations that aren't being considered here.

**Comment by caseyedavis12** [comment]
@afred: Yes, that is fine with me

**Pull request closed without merging**
