### PR TITLE
Degenerate year facet 148

### PR DESCRIPTION
**Pull request by mccalluc**
@afred? Alternatively, we could respect their reasons for doing it this way, and just fix the alignment in CSS.

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc can you post a visual of what it looks like?

**Comment by mccalluc** [comment]
With the tweaks, when there's one year in the facet it looks like:
screen shot 2016-02-10 at 3 55 12 pm

**Comment by afred** [comment]
@mccalluc @caseyedavis12 Hmm.... this is confusing, but it makes more sense than leaving year dangling over to the right.

Merging now, and if we feel we want something else, let's hash out what that might be.

**Comment by afred** [comment]
added #170 to revisit this after launch, unless @caseyedavis12 you want it to be a part of our initial launch.

**Comment by caseyedavis12** [comment]
@afred Yes, let's revisit after launch.

**Pull request merged**
