### PR TITLE
Update boston-tv-news.md

### PR DESCRIPTION
**Pull request by caseyedavis12**

### CODE REVIEW

**Comment by mccalluc** [comment]
@caseyedavis12 : All of these look good, except the thumb for #2, Evening Compass, is missing. Let me know when it's in place on S3.

**Comment by caseyedavis12** [comment]
@mccalluc: It was a URL issue in markdown. Fixed.

**Comment by mccalluc** [comment]
@caseyedavis12 : Do you intend to make a correction? I still only see your original commit here.

**Comment by caseyedavis12** [comment]
@mccalluc: I already made the correction in the fix-urls-1 branch.


________________________________

**Comment by mccalluc** [comment]
@caseyedavis12 : Something is confused: this is the `fix-urls-1` branch.

**Comment by caseyedavis12** [comment]
@mccalluc: I figured it out. It was fixed in #380 which you just closed and didn't merge.

**Comment by caseyedavis12** [comment]
@mccalluc: But I also just fixed it in #377, so feel free to just merge #377

**Pull request merged**
