### PR TITLE
Click here is bad

### PR DESCRIPTION
**Pull request by caseyedavis12**

### CODE REVIEW

**Comment by mccalluc** [comment]
@caseyedavis12 : The phrasing you've chosen
> Project staff and funding can be viewed on the **credits page**.
is almost exactly analogous to the style [w3c](https://www.w3.org/QA/Tips/noClickHere) says *not* to use.
> To download Amaya, go to the **Amaya Website** and get the necessary software.

**Comment by caseyedavis12** [comment]
Ok @mccalluc: Would you like to recommend a different phrase?

**Comment by afred** [comment]
Probably just "[View project staff and funding](/credits/credits-advocates)" ?

**Comment by mccalluc** [comment]
we could also put it in the table of contents list. (We had moved it out because it made the line of tabs even longer, and that's no longer a concern.)

**Comment by caseyedavis12** [comment]
@mccalluc @afred

"View project staff and funding" sounds good. I will make the edits.

Let's leave the pages as is, since there are some non-collection specific credits pages. I think it makes sense to have all the credits pages together.

**Pull request closed without merging**
