### PR TITLE
use -quality 50 jpegs instead of full pngs. Towards #539.

### PR DESCRIPTION
**Pull request by mccalluc**
@afred or @Muraszko ? imagemagick -quality 50 compression is aggressive, but I think it's hard to tell the difference, and we get a 10-fold reduction in size, so I think it's worth it, particularly on these pages that have so many images.

Artifacts are just starting to be noticeable (Lettering on signs where contrasting tones are separated by straight lines is the first thing to go fuzzy)... so I wouldn't want to push this much farther.

before closing #539
- Should we clear out the old ones on S3? At the very least, need to wait until this is deployed.
- Should we apply this level of compression across the board?

```
  32 scholar_exhibits/advocates/advocates_554x340-q-50.jpg
 104 scholar_exhibits/advocates/advocates_554x340.jpg
1832 scholar_exhibits/advocates/advocates_554x340.png

  40 scholar_exhibits/art_of_asian_cooking/art_of_asian_cooking_554x340-q-50.jpg
 104 scholar_exhibits/art_of_asian_cooking/art_of_asian_cooking_554x340.jpg
1744 scholar_exhibits/art_of_asian_cooking/art_of_asian_cooking_554x340.png

  24 scholar_exhibits/bibring/bibring_554x340-q-50.jpg
  80 scholar_exhibits/bibring/bibring_554x340.jpg
1512 scholar_exhibits/bibring/bibring_554x340.png

  24 scholar_exhibits/boring_and_sachs/boring_and_sachs_554x340-q-50.jpg
  64 scholar_exhibits/boring_and_sachs/boring_and_sachs_554x340.jpg
1184 scholar_exhibits/boring_and_sachs/boring_and_sachs_554x340.png

  48 scholar_exhibits/boston_civil_rights/boston_civil_rights_554x340-q-50.jpg
 128 scholar_exhibits/boston_civil_rights/boston_civil_rights_554x340.jpg
 512 scholar_exhibits/boston_civil_rights/boston_civil_rights_554x340.png

  40 scholar_exhibits/eric_jackson/eric_jackson_554x340-q-50.jpg
 112 scholar_exhibits/eric_jackson/eric_jackson_554x340.jpg
 696 scholar_exhibits/eric_jackson/eric_jackson_554x340.png

  24 scholar_exhibits/fenway_park/fenway_park_554x340-q-50.jpg
  72 scholar_exhibits/fenway_park/fenway_park_554x340.jpg
 464 scholar_exhibits/fenway_park/fenway_park_554x340.png

  24 scholar_exhibits/james_baldwin/james_baldwin_554x340-q-50.jpg
  48 scholar_exhibits/james_baldwin/james_baldwin_554x340.jpg
 368 scholar_exhibits/james_baldwin/james_baldwin_554x340.png

  48 scholar_exhibits/julia_child/julia_child_554x340-q-50.jpg
 128 scholar_exhibits/julia_child/julia_child_554x340.jpg
 736 scholar_exhibits/julia_child/julia_child_554x340.png

  32 scholar_exhibits/leary_and_jobs/leary_and_jobs_554x340-q-50.jpg
  72 scholar_exhibits/leary_and_jobs/leary_and_jobs_554x340.jpg
 408 scholar_exhibits/leary_and_jobs/leary_and_jobs_554x340.png

  40 scholar_exhibits/needlework/needlework_554x340-q-50.jpg
 120 scholar_exhibits/needlework/needlework_554x340.jpg
1840 scholar_exhibits/needlework/needlework_554x340.png

  24 scholar_exhibits/new_critical_television/new_critical_television_554x340-q-50.jpg
  64 scholar_exhibits/new_critical_television/new_critical_television_554x340.jpg
1376 scholar_exhibits/new_critical_television/new_critical_television_554x340.png

  32 scholar_exhibits/nine_poets/nine_poets_554x340-q-50.jpg
  80 scholar_exhibits/nine_poets/nine_poets_554x340.jpg
 376 scholar_exhibits/nine_poets/nine_poets_554x340.png

  48 scholar_exhibits/pan-african_liberation/pan-african_liberation_554x340-q-50.jpg
 104 scholar_exhibits/pan-african_liberation/pan-african_liberation_554x340.jpg
 616 scholar_exhibits/pan-african_liberation/pan-african_liberation_554x340.png

  40 scholar_exhibits/showing_status/showing_status_554x340-q-50.jpg
 120 scholar_exhibits/showing_status/showing_status_554x340.jpg
 592 scholar_exhibits/showing_status/showing_status_554x340.png

  32 scholar_exhibits/tech-nostalgia/tech-nostalgia_554x340-q-50.jpg
  80 scholar_exhibits/tech-nostalgia/tech-nostalgia_554x340.jpg
 504 scholar_exhibits/tech-nostalgia/tech-nostalgia_554x340.png

  32 scholar_exhibits/television_violence/television_violence_554x340-q-50.jpg
  80 scholar_exhibits/television_violence/television_violence_554x340.jpg
1280 scholar_exhibits/television_violence/television_violence_554x340.png

  32 scholar_exhibits/zoom/zoom_554x340-q-50.jpg
 104 scholar_exhibits/zoom/zoom_554x340.jpg
1888 scholar_exhibits/zoom/zoom_554x340.png

  40 special_collections/aapb/aapb-q-50.jpg
  88 special_collections/aapb/aapb.jpg
 288 special_collections/aapb/aapb.png

  32 special_collections/advocates/advocates-q-50.jpg
 104 special_collections/advocates/advocates.jpg
 464 special_collections/advocates/advocates.png

  32 special_collections/from_the_vault/from_the_vault-q-50.jpg
 128 special_collections/from_the_vault/from_the_vault.jpg
 680 special_collections/from_the_vault/from_the_vault.png

  40 special_collections/march_washington/march_washington-q-50.jpg
  96 special_collections/march_washington/march_washington.jpg
 336 special_collections/march_washington/march_washington.png

  24 special_collections/ntw/ntw-q-50.jpg
  72 special_collections/ntw/ntw.jpg
 224 special_collections/ntw/ntw.png

  24 special_collections/press_people/press_people-q-50.jpg
  64 special_collections/press_people/press_people.jpg
 304 special_collections/press_people/press_people.png

  40 special_collections/rock_roll/rock_roll-q-50.jpg
 208 special_collections/rock_roll/rock_roll.jpg
 752 special_collections/rock_roll/rock_roll.png

  48 special_collections/say_brother/say_brother-q-50.jpg
 136 special_collections/say_brother/say_brother.jpg
 752 special_collections/say_brother/say_brother.png

  32 special_collections/stock_sales/stock_sales-q-50.jpg
  88 special_collections/stock_sales/stock_sales.jpg
 408 special_collections/stock_sales/stock_sales.png

  40 special_collections/tocn/tocn-q-50.jpg
 104 special_collections/tocn/tocn.jpg
 352 special_collections/tocn/tocn.png

  32 special_collections/vietnam/vietnam-q-50.jpg
 104 special_collections/vietnam/vietnam.jpg
 496 special_collections/vietnam/vietnam.png

  16 special_collections/war_peace/war_peace-q-50.jpg
  64 special_collections/war_peace/war_peace.jpg
 264 special_collections/war_peace/war_peace.png
```

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc good work on this! I'm interested to see the results. Email some samples maybe?

**Comment by mccalluc** [comment]
@afred: Here's the one pair where I think a difference is really clear. For the rest, just get a checkout and look at it?

current PNG:
boston_civil_rights_554x340
proposed JPEG:
boston_civil_rights_554x340-q-50

**Comment by afred** [comment]
:+1: from me, but we should have some discussions around...

1. Are we generally OK with improving website speed at the cost of image quality?
1. Is there a minimum quality of image/video we are expected to deliver?
1. Currently, we are only offering one resolution of images/video, and so we have to settle on one that allows reasonable website performance, but also provides a satisfactory user experience. A common approach to offering the best of both worlds is to offer multiple resolutions.. but that is a big development ask.

the trade-off between speed and quality is a product manager decision.. so I'll defer the final :+1: to @Muraszko and @caseyedavis12 before merging this.

**Comment by caseyedavis12** [comment]
@mccalluc: The jpgs look fine to me. Can we keep the highest quality images on the homepage gallery, though?


cc @muraszko @afred

**Comment by caseyedavis12** [comment]
@mccalluc: Or can I see a comparison if you plan to change the homepage gallery images?


cc @afred @muraszko

**Comment by mccalluc** [comment]
@caseyedavis12 : This PR is only the collection and exhibit images. If you're ok with this, then please merge.

Homepage images are not touched here, and can be evaluated separately.

**Pull request merged**
