### PR TITLE
Fixes links to faceted searches

### LINKED ISSUE #193: Links to faceted search by Series title are being rewritten
**Reproduce:** following this link: `http://localhost:3000/catalog?f[series_title][]=Vietnam%3A+A+Television+History` will take you to this URL: `http://localhost:3000/catalog?f%5Baccess%5D%5B%5D=Available+Online`

**Note:** these links are found on the series list page: http://localhost:3000/series

Perhaps the logic that automatically sets the access level is accidentally getting rid of other facets?

**Done when** following a link to a faceted search by Series title actually does a search by the series title.

### PR DESCRIPTION
**Pull request by afred**
closes #193.

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc?

**Comment by mccalluc** [comment]
```
       expected: "f[access][]=Available+Online&q="
            got: "action=index&controller=catalog&f[access][]=Available+Online&q="
```

**Comment by afred** [comment]
@mccalluc i think the test just needs to be loosened up a bit. Stand by..

**Comment by afred** [comment]
@mccalluc now passing

**Pull request merged**
