### PR TITLE
Playlists

### PR DESCRIPTION
**Pull request by mccalluc**
@afred? (note that this would require a reingest, so probably don't merge if you've already started the one for today.)

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc screenshot?

**Comment by mccalluc** [comment]
@afred: new commit (which looks like it fails...) provides an example in the fixtures which looks like:
screen shot 2016-02-16 at 12 13 54 pm

(Could add a test, but would prefer not to add to the merge conflicts right now.)

**Comment by mccalluc** [comment]
@afred: Is this in good shape? Do you want to handle the conflicts?

**Comment by afred** [comment]
@mccalluc i took a look at the conflicts but realized it was going to take a minute to sort out `_player.html.erb`. You could probably do it faster.

Here's how i do the rebases, to avoid not-so-useful merge commits.
```bash
git checkout playlists
git rebase master
# then, after fixing conflicts in _player.html.erb
git add app/views/_player.html.erb
git rebase --continue
# everything should be rebased now
git push --dry-run -f
# and if everything looks ok...
git push -f
```

**Comment by mccalluc** [comment]
@afred?

**Pull request merged**
