### PR TITLE
Update about.md

### PR DESCRIPTION
**Pull request by caseyedavis12**
Can you show me what the images look like on the page? Are they aligned left with text wrap?

### CODE REVIEW

**Comment by mccalluc** [comment]
@caseyedavis12 : I've tweaked the MD around one image: Here's a screen shot for comparison. The images are over-sized... but since there's only two, the bandwidth waste doesn't really bother me. If you don't want it quite that small, tweak the class. Remember that you don't want to put in the image in a paragraph by itself.

Back to you?

screen shot 2016-02-25 at 10 33 10 am

**Comment by mccalluc** [comment]
@caseyedavis12 : Also, please use a real em-dash rather than "--".

Also, it doesn't make any difference to the way it renders, but having a line break after 80 columns or so will make it easier to read diffs of future edits... but not something I'll block on.

**Comment by mccalluc** [comment]
... and some content issues:
>
WGBH productions -- ... -- has 

subject verb agreement

>
We provide access to nearly 12,000 of these programs are available online at americanarchive.org.

Choose one predicate or the other.

>
If you are interested in supporting Open Vault through donation or sponsoring digitization, or contact us

Remove last or, add period.

This is quibbly, but on many URLs you are adding a www in front. This is generally harmless ... but there's actually no guarantee that www.example.org is the same as example.org.

**Comment by caseyedavis12** [comment]
@mccalluc: Sorry for overlooking these errors. Did you already fix or do you want me to fix?

**Pull request merged**
