### PR TITLE
Better sell for Broadcast Programs?

### LINKED ISSUE #613: Add text for items of "Asset type: Broadcast program" that points to ancillary material
**Done when** appropriate text has been crafted, and approved and added to the right pages.

### PR DESCRIPTION
**Pull request by mccalluc**
@Muraszko ?
screen shot 2016-05-03 at 11 04 27 am

Maybe run it by the folks who prompted this... or wait until it's deployed, and try then? Your call. Fix #613.

### CODE REVIEW

**Comment by Muraszko** [comment]
@mccalluc 
Talked with Karen and Casey, before we merge it, could you please change two things?

1) The text should be:
```
More material is available from this program at the WGBH Archive. If you are a researcher interested in accessing the collection at WGBH, please email openvault@wgbh.org.
```

2) Please move the outside URL links to AAPB and Boston Local above this text description to be at the top of the frame when exists on a record.
The order of things should be (from top to bottom) Outside URL, More material text, Digitize Buttons, Transcript

Thanks

**Comment by caseyedavis12** [comment]
@muraszko: I think Karen also wanted to put "if you are a researcher..." before "if you want to license footage..."


cc @mccalluc

________________________________

**Comment by Muraszko** [comment]
@caseyedavis12 @mccalluc 
Sorry, I talked with Karen and she doesn't want the licensing footage text in there at this time.
Thanks.

**Comment by mccalluc** [comment]
@Muraszko ?

**Pull request merged**
