### PR TITLE
Update carousel.md

### PR DESCRIPTION
**Pull request by caseyedavis12**

### CODE REVIEW

**Comment by afred** [comment]
@caseyedavis12 It doesn't look like any of the images have been uploaded yet

**Comment by caseyedavis12** [comment]
@afred: you are right. I am waiting on size instructions from digital


________________________________

**Comment by mccalluc** [comment]
@caseyedavis12 : any word on this? Are we waiting for the Friday meeting? That was not originally intended to be something that would block deployment, but whatever.

**Comment by caseyedavis12** [comment]
@mccalluc: Working on it. As I stated in my email last night, my work should be done by the meeting on Friday.

**Pull request merged**
